# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YCXjqNZf3GAaA-lnwUWwAKZ5eQxl4yZz
"""

[] PrincipalAmount = int(input('Enter principal amount'))
   Rate = float(input('Enter the rate of interest: '))
   Years = int (input('Enter number of Years'))
   #Divide the value by 100
   print()
   Interest = PrincipalAmount*(1 + ((Rate/100)*Years))
   print('After' , Years, 'Years at' , Rate , '%, the investment will be worth' , result)