# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NoBXKYke96rVf7Lepeor5mUs-mQ3cXtS
"""

[] amount= float(input('Enter order amount'))
   state = input('Enter state name')

    if state == 'W1':
    print()
    print('Subtotal' , amount)
    print('Tax' , amount*(5.5/100))
    print('Total amount after calculation', (amount*(5.5/100)) + amount)
    
    else
    print()
    print('Subtotal', amount)

"""# New Section

[link text](https:// [link text](https://))# New Section
"""