# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CZl4T6PddnQT_m1M9eQbt2APWZv8sIPO
"""

temp= input('Press C to convert to Celsius and F to convert to Farenhit')
if temp.islower():
   temp = temp.upper()
   print ('Your temp: ', temp, end ='/n/n')


   if temp == 'C'
   print()
   f = int(input('Please enter the temprature in Fahrenheit: '))
   print('The temprature in Celsuis is ' ,  ((f-32) * (5/9)) )


   elif temp == 'F':
   print()
   C= input(input('Please enter the temprature in Celsius: '))
   print = ('The temprature in Farenhit is' , ((C* (9/5)) + 32))

   else 
   print('Invalid number' , temp)