# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18n8S3f9P1jtoQ8eOSeZObFFo4qrOm6Uj
"""

password= 'abc123'

pass= input('Enter password')
if pass == password:
   print('Welcome')
else:
(print('Username or password inccorrect'))